apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: position-trajectory-controller
  labels:
    app: starling

spec:
  selector:
    matchLabels:
      name: position-trajectory-controller

  template:
    metadata:
      labels:
        name: position-trajectory-controller

    spec:
      nodeSelector:
        starling.dev/vehicle-class: rotary

      tolerations:
      - key: "starling.dev/type"
        operator: "Equal"
        value: "vehicle"
        effect: "NoSchedule"

      hostNetwork: true
      shareProcessNamespace: true

      containers:
      - name: position-trajectory-controller
        image: uobflightlabstarling/position-trajectory-controller
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/starling/vehicle.config
          name: vehicleconfig
          readOnly: true

      volumes:
      - name: vehicleconfig
        hostPath:
          path: /etc/starling/vehicle.config
          type: File